version: "3"
services:
  app:
    build: .
    ports:
      - "8082:8082"
    restart: always
    env_file:
      - .env
    networks:
      - sagarmathalabs_network

  # worker:
  #   build: .
  #   command: python worker.py
  #   restart: always
  #   env_file:
  #     - .env
  #   networks:
  #     - sagarmathalabs_network

networks:
  sagarmathalabs_network:
    external: true